language: bash

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=3.7

before_install:
  # double check the installed versions
  - docker version
  - docker-compose version

install:
  - docker-compose up -d

script:
  # Travis appears to only have 16 char container names.
  - docker-compose ps | grep "nldi_Database\s.*Up"
  - docker-compose ps | grep "nldi_Database_DE.*Up"
  - docker-compose ps | grep "nldi_Database_CI.*Up"
  - docker-compose ps | grep "nldi_liquibase\s.*Exit 0"
  