language: bash

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=3.7

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose up -d

script:
  # Travis appears to only have 16 char container names.
  - docker-compose ps | grep "nldi_Database\s.*Up"
  - docker-compose ps | grep "nldi_Database_DE.*Up"
  - docker-compose ps | grep "nldi_Database_CI.*Up"
  - docker-compose ps | grep "nldi_liquibase\s.*Exit 0"
  