language: bash

services:
  - docker

before_install:
  # double check the installed versions
  - docker version
  - docker-compose version

install:
  - docker-compose up -d

script:
  - docker images
  # Travis appears to only have 16 char container names, so NLDI_Database_Volume gets truncated.
  - docker-compose ps | grep "NLDI_Database_Vo.*Exit 0"
  - docker-compose ps | grep "NLDI_Database\s.*Up"
  - docker-compose ps | grep "NLDI_Database_De.*Up"
  - docker-compose ps | grep "NLDI_Database_CI.*Up"
