version: '3.7'
services:

  ciDB:
    image: nldi_db_ci
    build:
      context: .
      dockerfile: ./database/ci/Dockerfile
    networks:
      nldi:
        ipv4_address: ${DB_CI_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${NLDI_DATABASE_NAME}
      - NLDI_DATABASE_NAME=${NLDI_DATABASE_NAME}
      - NLDI_DB_OWNER_USERNAME=${NLDI_DB_OWNER_USERNAME}
      - NLDI_DB_OWNER_PASSWORD=${NLDI_DB_OWNER_PASSWORD}
      - NLDI_SCHEMA_OWNER_USERNAME=${NLDI_SCHEMA_OWNER_USERNAME}
      - NLDI_SCHEMA_OWNER_PASSWORD=${NLDI_SCHEMA_OWNER_PASSWORD}
      - NHDPLUS_SCHEMA_OWNER_USERNAME=${NHDPLUS_SCHEMA_OWNER_USERNAME}
      - NLDI_READ_ONLY_USERNAME=${NLDI_READ_ONLY_USERNAME}
      - NLDI_READ_ONLY_PASSWORD=${NLDI_READ_ONLY_PASSWORD}
      - NLDI_DATABASE_ADDRESS=127.0.0.1
    ports:
      - ${DB_CI_PORT}:5432
    container_name: ${NLDI_DATABASE_NAME}_CI

  nldi_db_demo:
#    depends_on:
#      - nldi_db
    build:
      context: .
      dockerfile: Dockerfile.demo
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=nldi
      - POSTGRES_DB=nldi
      - NLDI_PASSWORD=nldi
      - NLDI_DATA_PASSWORD=nldi
      - NLDI_USER_PASSWORD=nldi
    container_name: NLDI_Database_Demo


networks:
  nldi:
    external:
      name: ${LOCAL_NETWORK_NAME}
