version: '2'
services:
  nldi_db_vol_container:
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: /bin/echo "Data only container for NLDI PostGRES"
    labels:
      - "gov.usgs.owi.nldi.container.volume=true"
    container_name: NLDI_Database_Volume
  nldi_db:
    build:
      context: .
    volumes_from: 
      - nldi_db_vol_container
    environment:
      - POSTGRES_PASSWORD=nldi
      - POSTGRES_DB=nldi
      - NLDI_PASSWORD=nldi
      - NLDI_DATA_PASSWORD=nldi
      - NLDI_USER_PASSWORD=nldi
    container_name: NLDI_Database
  nldi_db_demo:
    depends_on:
      - nldi_db
    build:
      context: ./nldi-demo-db
    volumes_from: 
      - nldi_db_vol_container
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=nldi
      - POSTGRES_DB=nldi
      - NLDI_PASSWORD=nldi
      - NLDI_DATA_PASSWORD=nldi
      - NLDI_USER_PASSWORD=nldi
    container_name: NLDI_Database_Demo
  nldi_db_ci:
    depends_on:
      - nldi_db
    build:
      context: ./nldi-ci-db
    volumes_from: 
      - nldi_db_vol_container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=nldi
      - POSTGRES_DB=nldi
      - NLDI_PASSWORD=nldi
      - NLDI_DATA_PASSWORD=nldi
      - NLDI_USER_PASSWORD=nldi
    container_name: NLDI_Database_CI
