version: '2'
services:
  nldi_db:
    image: nldidb_nldi_db
    build:
      context: .
      dockerfile: Dockerfile.base
    environment:
      - POSTGRES_PASSWORD=nldi
      - POSTGRES_DB=nldi
      - NLDI_PASSWORD=nldi
      - NLDI_DATA_PASSWORD=nldi
      - NLDI_USER_PASSWORD=nldi
    container_name: NLDI_Database
  nldi_db_demo:
    depends_on:
      - nldi_db
    build:
      context: .
      dockerfile: Dockerfile.demo
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=nldi
      - POSTGRES_DB=nldi
      - NLDI_PASSWORD=nldi
      - NLDI_DATA_PASSWORD=nldi
      - NLDI_USER_PASSWORD=nldi
    container_name: NLDI_Database_Demo
  nldi_db_ci:
    depends_on:
      - nldi_db
    build:
      context: .
      dockerfile: Dockerfile.ci
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=nldi
      - POSTGRES_DB=nldi
      - NLDI_PASSWORD=nldi
      - NLDI_DATA_PASSWORD=nldi
      - NLDI_USER_PASSWORD=nldi
    container_name: NLDI_Database_CI
